[package]
name = "rusty_dashed"
version = "0.1.0"
authors = ["Hugo Freire <hfreire@abajar.com>"]

build = "build.rs"

[dependencies]
mio = "0.6"
staticfile = "*"
iron = "*"
hyper = "*"
mount = "*"
phf = "0.7.12"
includedir = "0.2.0"
ws = "0.5.3"
log = "*"
env_logger = "*"
lazy_static = "0.1.*"

[build-dependencies]
includedir_codegen = "0.2.0"

[features]
default = ["serve_static"]

serve_static = []

debug_static = []
