[package]
name = "rusty_dashed"
version = "0.1.0"
authors = ["Hugo Freire <hfreire@abajar.com>"]

build = "build.rs"
include = ["public"]

[dependencies]
mio = "0.6"
staticfile = "*"
iron = "*"
mount = "*"
phf = "0.7.12"
includedir = "0.2.0"

[build-dependencies]
includedir_codegen = "0.2.0"
